version: '2'
services:
 webshop-db:
   image: mavogel/vis-web-shop-db-image
   volumes:
     - "./.data/db:/var/lib/mysql"
   environment:
     MYSQL_ROOT_PASSWORD: c8de110f37300a53a971749
     MYSQL_DATABASE: webshop
     MYSQL_USER: webshopuser
     MYSQL_PASSWORD: 240b2c6d58ff2ce2f508b49f
   ports:
     - "3306:3306"

 categoryservice:
   depends_on:
     - webshop-db
   image: mavogel/vis-categoryservice
   links:
     - webshop-db:web-shop-db-image
   environment:
     MYSQL_WEBSHOP_DB_ADDR: web-shop-db-image
     MYSQL_WEBSHOP_DB_PORT: 3306
     MYSQL_WEBSHOP_DB_DATABASE: webshop
     MYSQL_WEBSHOP_DB_USER: webshopuser
     MYSQL_WEBSHOP_DB_PASSWORD: 240b2c6d58ff2ce2f508b49f
#   ports:
#     - "8081:8080"

 productservice:
   depends_on:
     - webshop-db
   image: mavogel/vis-productservice
   links:
     - webshop-db:web-shop-db-image
   environment:
     MYSQL_WEBSHOP_DB_ADDR: web-shop-db-image
     MYSQL_WEBSHOP_DB_PORT: 3306
     MYSQL_WEBSHOP_DB_DATABASE: webshop
     MYSQL_WEBSHOP_DB_USER: webshopuser
     MYSQL_WEBSHOP_DB_PASSWORD: 240b2c6d58ff2ce2f508b49f
#   ports:
#     - "8082:8080"

 userservice:
   depends_on:
     - webshop-db
   image: mavogel/vis-userservice
   links:
     - webshop-db:web-shop-db-image
   environment:
     MYSQL_WEBSHOP_DB_ADDR: web-shop-db-image
     MYSQL_WEBSHOP_DB_PORT: 3306
     MYSQL_WEBSHOP_DB_DATABASE: webshop
     MYSQL_WEBSHOP_DB_USER: webshopuser
     MYSQL_WEBSHOP_DB_PASSWORD: 240b2c6d58ff2ce2f508b49f
#   ports:
#     - "8083:8080"

 categorycompositeservice:
   image: mavogel/vis-categorycompositeservice
#   ports:
#     - "8084:8080"

 discovery:
   image: mavogel/vis-discovery
   ports:
     - "8761:8761"

 api-gateway:
   image: mavogel/vis-api-gateway
   ports:
     - "8765:8765"

 dashboard:
   image: mavogel/vis-dashboard
   links:
     - categorycompositeservice
     - api-gateway
   ports:
     - "7979:7979"

 uaa-service:
   image: mavogel/vis-uaa-service
#   ports:
#     - "8769:8769"

 dummy-service:
   image: mavogel/vis-dummy-service
#   ports:
#     - "8870:8870"

 legacywebshop-micro:
   image: mavogel/vis-legacywebshop-micro
   links:
     - api-gateway
   ports:
     - "8899:8080"

 legacywebshop:
   image: mavogel/vis-legacywebshop
   links:
     - webshop-db:web-shop-db-image
   ports:
     - "8888:8080"